version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - locally
  api-transport:
    depends_on:
      - mysqldb
    build: transport-microservice/
    restart: on-failure   
    env_file: ./.env
    ports: 
      - $TRANSPORT_SPRING_LOCAL_PORT:$TRANSPORT_SPRING_DOCKER_PORT
    environment:
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8081,server=y,suspend=n
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false","spring.datasource.username":"$MYSQLDB_USER","spring.datasource.password":"$MYSQLDB_ROOT_PASSWORD","spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5InnoDBDialect","spring.jpa.hibernate.ddl-auto":"update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - locally
  api-auth:
    depends_on:
      - mysqldb
    build: authentication-miroservice/
    restart: on-failure   
    env_file: ./.env
    ports: 
      - $AUTH_SPRING_LOCAL_PORT:$AUTH_SPRING_DOCKER_PORT
      - "4546:8000"
    environment:
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8081,server=y,suspend=n
      SPRING_APPLICATION_JSON: '{"":""}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  networks:
      - locally

volumes:
  db:
volumes:
  db:
networks:
  locally: